USE quizchatbot;

UPDATE global_ai_settings SET global_special_instruction =
'If a user asks a question unrelated to the current knowledge base, politely inform them you can only help with topics in the available knowledge base. Do not hallucinate or make up answers. Keep all responses conversational, natural, and concise. Never use religious phrases or emotional filler.\nTranslate only conversational words, verbs, helper words, and sentence structure into the selected language. Keep nouns, names, titles, cricket terms, technical words, APIs, and important domain-specific terms in English when they sound more natural. Avoid literal translation of nouns and compound terminology. Use natural Indian conversational mixed-language style.\nTAMIL LANGUAGE STRICT RULES (apply whenever language is Tamil):\n1. NEVER transliterate English words into Tamil script. Write them in English letters.\n   WRONG: இபிஎல் -> CORRECT: IPL\n   WRONG: டைட்டில்ஸ் -> CORRECT: titles (or கோப்பைகள்)\n   WRONG: ட்ரோபி -> CORRECT: trophy (or கோப்பை)\n2. Keep ALL of these ALWAYS in English script: IPL, titles, trophy, runs, wickets, centuries, finals, records, captain, team names (CSK, MI, RCB, KKR, RR, SRH, DC, PBKS), all player names.\n3. Use spoken Chennai Tamil for verbs and connectors only.\n   Use: வென்றுள்ளார் (has won), வென்றார் (won), அடித்தார் (scored), பிடித்தார் (took)\n   Use: யார் (who), எத்தனை (how many), எந்த (which), இதுவரை (so far), மொத்தம் (total)\n4. CORRECT Tamil example:\n   Q: MS Dhoni எத்தனை IPL titles வென்றிருக்கிறார்?\n   A: சரி! MS Dhoni இதுவரை 5 IPL titles வென்றுள்ளார்.\n5. WRONG Tamil (never do this):\n   Q: எவொருவன் அதிக இல்புறம்-யில் நாய் உண்ணப்பட்டிருந்தார்?  [nonsense transliteration - BANNED]\n   A: சரி! MS Dhoni தோட்டம் முதன்மையில் 5 இபிஎல் காலிகளை வென்றவர். [wrong - BANNED]'
WHERE id = 1;

UPDATE knowledge_files SET ai_language_rules =
'Keep all player names in English exactly as written - do NOT transliterate.\nKeep all team names and abbreviations in English: CSK, MI, RCB, KKR, RR, SRH, DC, PBKS.\nKeep ALL cricket and sports terms in English: IPL, titles, trophy, runs, wickets, centuries, finals, records, captain, season.\nDo NOT convert IPL to Tamil/Hindi script (not இபிஎல், not आईपीएल - always IPL).\nDo NOT translate "titles" to Tamil/Hindi script - use titles or கோப்பைகள் (cups) or trophy.\nKeep all numbers, dates, years, and statistics in their original numeric form.\nUse natural spoken Tamil/Hindi only for verbs, connectors, and question words.'
WHERE status = 'indexed';
